version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - ./data/visits:/app/data/visits
    environment:
      - NODE_ENV=production
    restart: unless-stopped 